version: '3.8'
services:
  gateway:
    container_name: shareit-api-gateway
    build: gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    container_name: shareit-server
    build: server
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit?encoding=utf8
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=9090

  db:
    container_name: shareit-database
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - /var/lib/postgresql/data/
      - ./server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql